### ISSUE TITLE
有关attention疑问

### ISSUE THREAD

**Issue by yanhan19940405** [stevewyl/keras_text_classification#1]
你好，我这里只看到你的word attention层，那么请问后面那一层sentence attention层你又怎么处理的呢？

**Comment by stevewyl** [comment]
@yanhan19940405 可以参考我的另一个repo中的HAN实现 链接：https://github.com/stevewyl/comparative-reviews-classification/blob/master/model_library.py

**Comment by yanhan19940405** [comment]
好的，多谢，我研究研究
