### ISSUE TITLE
有关attention模型input疑问

### ISSUE THREAD

**Issue by yanhan19940405** [stevewyl/keras_text_classification#2]
你好，请问你的attention第一层input是指什么结构的数据来fit模型啊？我看到shape=(20,),请问这个20是指maxseq值呢？还是指什么呀？我目前有多个新闻文本数据，每个文本里面有多个句子，想学着做新闻主题分类，目前想请教下具体fit的结构是啥样的呢？麻烦指点下呢

**Comment by stevewyl** [comment]
@yanhan19940405 你可以将文本进行分句。这里的20表示的是你每个句子的最大词数，同时你也需要设置每个文本最多的句子数
