### ISSUE TITLE
ValueError: Found input variables with inconsistent numbers of samples: [12518, 37554]

### ISSUE THREAD

**Issue by bluesky632** [stevewyl/keras_text_classification#3]
您好,在jd文件夹下的ml_text_classification.py里，报错ValueError: Found input variables with inconsistent numbers of samples: [12518, 37554]；
报错代码是这句：bayes_clf.fit(x_train, y_train)

**Comment by stevewyl** [comment]
@bluesky632 代码已更新，测试通过，请查阅

**Comment by bluesky632** [comment]
好的，非常感谢
